<?php
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/mailer.php';
$cfg=require __DIR__ . '/../config/momo.php';
ensure_payment_schema();
function momo_sig(array $data,string $secret): string { ksort($data); $raw=[]; foreach($data as $k=>$v) if($k!=='signature') $raw[]=$k.'='.$v; return hash_hmac('sha256', implode('&',$raw), $secret); }
$action=$_GET['action'] ?? 'create';
if($action==='create'){ $orderId=(int)$_GET['order_id']; $stmt=db()->prepare('SELECT * FROM orders WHERE id=?'); $stmt->execute([$orderId]); $o=$stmt->fetch(); if(!$o) exit('Không tìm thấy đơn hàng'); if($o['payment_method'] !== 'MOMO') exit('Phương thức thanh toán không hợp lệ'); $requestId=$o['code'].'-'.time(); $data=['partnerCode'=>$cfg['partner_code'],'partnerName'=>'ShoeStore','storeId'=>'ShoeStore','requestId'=>$requestId,'amount'=>(string)(int)$o['total'],'orderId'=>$o['code'],'orderInfo'=>'Thanh toán '.$o['code'],'redirectUrl'=>$cfg['return_url'],'ipnUrl'=>$cfg['ipn_url'],'lang'=>'vi','requestType'=>'captureWallet','extraData'=>'']; $data['signature']=momo_sig(['accessKey'=>$cfg['access_key'],'amount'=>$data['amount'],'extraData'=>'','ipnUrl'=>$data['ipnUrl'],'orderId'=>$data['orderId'],'orderInfo'=>$data['orderInfo'],'partnerCode'=>$data['partnerCode'],'redirectUrl'=>$data['redirectUrl'],'requestId'=>$requestId,'requestType'=>$data['requestType']],$cfg['secret_key']); db()->prepare("UPDATE payments SET status='pending', payment_attempts=payment_attempts+1 WHERE order_id=? AND provider='MOMO'")->execute([$orderId]); $ch=curl_init($cfg['endpoint']); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($data),CURLOPT_TIMEOUT=>20]); $raw=curl_exec($ch); $res=json_decode($raw ?: '{}',true); db()->prepare('INSERT INTO payment_logs(provider,action,payload,valid_signature) VALUES(?,?,?,?)')->execute(['MOMO','create_payment_request',json_encode(['request'=>$data,'response'=>$res],JSON_UNESCAPED_UNICODE),isset($res['payUrl'])?1:0]); if(!empty($res['payUrl'])){ header('Location: '.$res['payUrl']); exit; } flash('error','Không tạo được URL thanh toán MoMo. Vui lòng kiểm tra cấu hình MoMo hoặc thử lại.'); header('Location: ' . app_url('user/orders.php')); exit; }
$payload=$_POST ?: $_GET; $valid=isset($payload['signature']) && hash_equals($payload['signature'], momo_sig($payload,$cfg['secret_key'])); $success=$valid && (string)($payload['resultCode'] ?? '')==='0'; $code=$payload['orderId'] ?? '';
$stmt=db()->prepare('SELECT p.id payment_id,o.id order_id,o.*,u.email FROM orders o JOIN payments p ON p.order_id=o.id JOIN users u ON u.id=o.user_id WHERE o.code=?'); $stmt->execute([$code]); $row=$stmt->fetch();
if($row){ $amountOk=((int)($payload['amount'] ?? 0)===(int)$row['total']); db()->prepare('INSERT INTO payment_logs(payment_id,provider,action,payload,valid_signature) VALUES(?,?,?,?,?)')->execute([$row['payment_id'],'MOMO',$action,json_encode($payload),($valid&&$amountOk)?1:0]); if($success && $amountOk){ db()->prepare("UPDATE payments SET status='paid',transaction_id=?,raw_response=? WHERE id=?")->execute([$payload['transId'] ?? null,json_encode($payload),$row['payment_id']]); db()->prepare("UPDATE orders SET status='waiting_confirm' WHERE id=?")->execute([$row['order_id']]); clear_paid_cart_items((int)$row['order_id']); create_notification((int)$row['user_id'],'Thanh toán MoMo thành công','Đơn hàng '.$row['code'].' đã thanh toán thành công.'); notify_admins('Thanh toán MoMo thành công','Đơn hàng '.$row['code'].' đã được thanh toán.'); send_mail($row['email'],'Thanh toán MoMo thành công '.$row['code'],'<p>Đơn hàng '.$row['code'].' đã thanh toán thành công.</p>'); audit_log('payment_success','orders',(int)$row['order_id'],['provider'=>'MOMO']); } else { db()->prepare("UPDATE payments SET status='failed',raw_response=? WHERE id=?")->execute([json_encode($payload),$row['payment_id']]); db()->prepare("UPDATE orders SET status='pending_payment' WHERE id=?")->execute([$row['order_id']]); create_notification((int)$row['user_id'],'Thanh toán MoMo thất bại','Đơn hàng '.$row['code'].' thanh toán thất bại hoặc sai signature. Sản phẩm vẫn được giữ trong giỏ hàng.'); audit_log('payment_failed','orders',(int)$row['order_id'],['provider'=>'MOMO','valid'=>$valid,'amount_ok'=>$amountOk]); } }
if($action==='ipn') json_response(['resultCode'=>$success?0:1,'message'=>$success?'Success':'Invalid signature']);
flash($success?'success':'error',$success?'Thanh toán MoMo thành công.':'Thanh toán MoMo thất bại hoặc sai signature.');
header('Location: ' . app_url('user/orders.php'));
